{
 "title": "PayVault Wallet Overview",
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "wallet_active_users_total" }
   ]
  },
  {
   "title": "Total Balance (INR)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyINR" } },
   "targets": [
    { "expr": "wallet_total_balance_inr" }
   ]
  },
  {
   "title": "Fraud Flags 5m",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "increase(wallet_transactions_total{status='blocked_fraud'}[5m])"
    }
   ]
  },
  {
   "title": "HTTP Requests/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(wallet_http_requests_total{status=~'2..'}[1m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(wallet_http_requests_total{status=~'5..'}[1m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "API Latency p95",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,rate(wallet_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Transaction Volume INR/min",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(wallet_transaction_amount_inr_sum{type='debit'}[1m])*60",
     "legendFormat": "Debit"
    },
    {
     "expr": "rate(wallet_transaction_amount_inr_sum{type='credit'}[1m])*60",
     "legendFormat": "Credit"
    }
   ]
  }
 ]
}