input {
  tcp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  if [service] == "wallet-backend" {

    if [message] =~ /FRAUD|fraud|BLOCKED|blocked_fraud/ {
      mutate { add_tag => ["fraud_alert"] }
    }

    if [message] =~ /TRANSFER|ADD_MONEY|transfer|credit|debit/ {
      mutate { add_tag => ["transaction"] }
    }

    if [message] =~ /LOGIN_FAILED|REGISTER|LOGIN_SUCCESS/ {
      mutate { add_tag => ["auth_event"] }
    }

    grok {
      match => { "message" => "amount=%{NUMBER:transaction_amount:float}" }
      tag_on_failure => []
    }

    mutate {
      add_field => {
        "environment" => "production"
        "project"     => "payvault"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "wallet-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}